//
//  homeInteractor.swift
//  BellmanAppTask
//
//  Created Mohamed Korany Ali on 1/26/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class homeInteractor: homeInteractorInputProtocol {

    weak var presenter: homeInteractorOutputProtocol?
}
