//
//  homeProtocols.swift
//  BellmanAppTask
//
//  Created Mohamed Korany Ali on 1/26/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol homeWireframeProtocol: class {

}
//MARK: Presenter -
protocol homePresenterProtocol: class {

    var interactor: homeInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol homeInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol homeInteractorInputProtocol: class {

    var presenter: homeInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol homeViewProtocol: class {

    var presenter: homePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
