//
//  homePresenter.swift
//  BellmanAppTask
//
//  Created Mohamed Korany Ali on 1/26/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class homePresenter: homePresenterProtocol, homeInteractorOutputProtocol {

    weak private var view: homeViewProtocol?
    var interactor: homeInteractorInputProtocol?
    private let router: homeWireframeProtocol

    init(interface: homeViewProtocol, interactor: homeInteractorInputProtocol?, router: homeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
