//
//  homeViewController.swift
//  BellmanAppTask
//
//  Created Mohamed Korany Ali on 1/26/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class homeViewController: UIViewController, homeViewProtocol {

	var presenter: homePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
